[package]
name = "avn-node-parachain"
description = "A Cumulus FRAME-based Substrate Node compatible with the AvN parachain"
license = "GPL-3.0"
build = "build.rs"

version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "avn-parachain-collator"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4.20"
codec = { package = "parity-scale-codec", version = "3.6.1" }
serde = { version = "1.0.195", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }
hex-literal = "0.4.1"
hex = "0.4"
serde_json = { version = "1.0.111", features = ["arbitrary_precision"] }

futures = "0.3.21"
cfg-if = "0.1"

# Local
runtime-common = { package = "avn-runtime-common", path = "../runtime/common" }
avn-parachain-runtime = { path = "../runtime/avn", optional = true }
avn-test-runtime = { package = "avn-parachain-test-runtime", path = "../runtime/test", optional = true }

# Substrate
frame-benchmarking = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
frame-benchmarking-cli = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
pallet-transaction-payment-rpc = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-basic-authorship = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-chain-spec = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-cli = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-client-api = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-offchain = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-consensus = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-executor = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-keystore = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-network = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-network-sync = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-network-common = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-rpc = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-service = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-sysinfo = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-telemetry = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-tracing = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-transaction-pool = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-transaction-pool-api = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-api = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-block-builder = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-blockchain = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-consensus-aura = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-core = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-keystore = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-offchain = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-io = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-runtime = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-session = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-timestamp = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-transaction-pool = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
substrate-frame-rpc-system = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
substrate-prometheus-endpoint = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
try-runtime-cli = { git = "https://github.com/energywebfoundation/polkadot-sdk", optional = true, branch = "polkadot-release-v1.6.0-233-hotfix" }
node-primitives = { version = "2.0.0", git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }

# AvN dependencies
sp-authority-discovery = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
pallet-im-online = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-avn-common = { path = "../primitives/avn-common"}

# Polkadot
polkadot-cli = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
polkadot-primitives = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
polkadot-service = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
xcm = { package = "staging-xcm", git = "https://github.com/energywebfoundation/polkadot-sdk", default-features = false, branch = "polkadot-release-v1.6.0-233-hotfix" }

# Cumulus
cumulus-client-cli = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-collator = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-consensus-aura = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-consensus-common = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-consensus-proposer = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-network = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-client-service = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-primitives-core = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
cumulus-relay-chain-interface = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }

# AvN
avn-service = { path = "avn-service" }
pallet-eth-bridge = { path = "../pallets/eth-bridge" }
pallet-eth-bridge-runtime-api = { path = "../pallets/eth-bridge/runtime-api" }

pallet-avn = { path = "../pallets/avn", default-features = false }
web3 = { version = "0.18.0", features = ["signing"] }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }

[features]
default = ["avn-native-runtime"]
runtime-benchmarks = [
    "cumulus-primitives-core/runtime-benchmarks",
    "frame-benchmarking-cli/runtime-benchmarks",
    "frame-benchmarking/runtime-benchmarks",
    "polkadot-cli/runtime-benchmarks",
    "polkadot-primitives/runtime-benchmarks",
    "sc-service/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "avn-parachain-runtime?/runtime-benchmarks",
    "avn-test-runtime?/runtime-benchmarks",
    "polkadot-cli/runtime-benchmarks",
]
try-runtime = [
    "try-runtime-cli/try-runtime",
    "polkadot-cli/try-runtime",
    "avn-parachain-runtime?/try-runtime",
    "avn-test-runtime?/try-runtime",
]

rococo-spec-build = []
avn-native-runtime = ["avn-parachain-runtime"]
test-native-runtime = ["avn-test-runtime"]

[dev-dependencies]
tempfile = "3.1.0"
sp-version = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
