[package]
name = "client-extrinsic-utils"

version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "3.6.1" }
log = "0.4.20"
serde = "1.0.163"
anyhow = "1.0.64"

# primitives
sp-core = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sp-runtime = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }

# client dependencies
sc-service = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-client-api = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-client-db = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-transaction-pool = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }
sc-transaction-pool-api = { git = "https://github.com/energywebfoundation/polkadot-sdk", branch = "polkadot-release-v1.6.0-233-hotfix" }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.4.1"
